//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور جدید.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را فراموش کرده اید ؟.
        /// </summary>
        internal static string login16 {
            get {
                return ResourceManager.GetString("login16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک معتبر نمی باشد.
        /// </summary>
        internal static string login6 {
            get {
                return ResourceManager.GetString("login6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        internal static string pas1 {
            get {
                return ResourceManager.GetString("pas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور با تایید آن مطابقت ندارد.
        /// </summary>
        internal static string pas2 {
            get {
                return ResourceManager.GetString("pas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبورصحیح نیست.
        /// </summary>
        internal static string pas3 {
            get {
                return ResourceManager.GetString("pas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد حروف کلمه عبور بایستی حداقل 6 کاراکتر باشد.
        /// </summary>
        internal static string pasLenth {
            get {
                return ResourceManager.GetString("pasLenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد حروف کلمه عبور بایستی حداقل 6 کاراکتر باشد.
        /// </summary>
        internal static string pasLenth1 {
            get {
                return ResourceManager.GetString("pasLenth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی کلمه عبور.
        /// </summary>
        internal static string pasres1 {
            get {
                return ResourceManager.GetString("pasres1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل خود را جهت بازنشانی کلمه عبور چک کنید.
        /// </summary>
        internal static string pasres4 {
            get {
                return ResourceManager.GetString("pasres4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا لینک زیر را جهت بازنشانی کلمه عبور کلیک کنید.
        /// </summary>
        internal static string pasres5 {
            get {
                return ResourceManager.GetString("pasres5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  کلمه عبور جدید.
        /// </summary>
        internal static string pasres6 {
            get {
                return ResourceManager.GetString("pasres6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی کلمه عبور.
        /// </summary>
        internal static string pasres7 {
            get {
                return ResourceManager.GetString("pasres7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ورود کلیک کنید.
        /// </summary>
        internal static string pasres8 {
            get {
                return ResourceManager.GetString("pasres8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور انجام شد.
        /// </summary>
        internal static string pchanged {
            get {
                return ResourceManager.GetString("pchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرتال تولیدکنندگان.
        /// </summary>
        internal static string prjTitle {
            get {
                return ResourceManager.GetString("prjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب کاربری جدید.
        /// </summary>
        internal static string reg1 {
            get {
                return ResourceManager.GetString("reg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید کلمه عبور.
        /// </summary>
        internal static string reg2 {
            get {
                return ResourceManager.GetString("reg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات انجام شد..
        /// </summary>
        internal static string reg8 {
            get {
                return ResourceManager.GetString("reg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصات کاربر.
        /// </summary>
        internal static string reg9 {
            get {
                return ResourceManager.GetString("reg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخاطر سپرده شود؟.
        /// </summary>
        internal static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود اطلاعات برای این فیلد اجباری است.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید مرحله دوم.
        /// </summary>
        internal static string stow {
            get {
                return ResourceManager.GetString("stow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test text.
        /// </summary>
        internal static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        internal static string wlc {
            get {
                return ResourceManager.GetString("wlc", resourceCulture);
            }
        }
    }
}
